number1 = int(input("Enter first number:"))
number2 = int(input("Enter second number:"))
print("Addition:", number1 + number2)
print("Subtraction:", number1 - number2)
print("Multiplication:", number1 * number2)
print("Division:", number1 / number2)